server:
  port: 8081
spring:
  application:
    name: demo
  resources:
    static-locations: classpath:/resources/,classpath:/resource/
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/adm?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.100.7
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: -1
        max-idle: 20
        min-idle: 2
    timeout: 5000
    password: password
mybatis-plus:
  mapper-locations: classpath*:/mybatis/**/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: true
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
    cache-enabled: true
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://192.168.100.230:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

